### ISSUE TITLE
Footer social links

### ISSUE THREAD

**Issue by electrickite** [osu-eng/mailit#8]
The social media links in the footer may not be generic or customizable enough. Should we remove them? Provide more templates? Make them user editable?

**Comment by jasonlttl** [comment]
Maybe there should be some link fields with reasonable (engineering specific) defaults and some custom token handling so all links could be output in a pipe delimited list.

link1 | link2 | link3

**Comment by jasonlttl** [comment]
Social links are now configureable.  In addition, users can specify up to six additional links as supported by the template.
